export type UserType = {
  id: number;
  username: string;
  email: string;
  provider: "local";
  confirmed: false;
  blocked: false;
  role: {
    id: number;
    name: "Authenticated";
    description: "Default role given to authenticated user.";
    type: "authenticated";
  };
  nickname: string;
  profile_image: string | null;
  point: 0;
  greeting: string;
  device_type: string;
  device_token: string | null;
  access_token: string | null;
  refresh_token: string | null;
  refresh_token_expire: string | null;
  phone: string | null;
  os: string | null;
  phone_verified_at: string | null;
  device: string | null;
  last_logined_at: string | null;
  last_logined_ip: string | null;
  birth: string | null;
  deleted_at: string | null;
  socket_status: string | null;
  socket_room: string | null;
  socket_id: string | null;
  gender: string | null;
  badge_message: string | null;
  badge_shop: string | null;
  badge_my: string | null;
  created_at: string//"2021-11-06T08:40:56.000Z";
  updated_at: string//"2021-11-06T08:40:56.000Z";
};
